services:
  # Service for running the pipeline scripts
  pipeline:
    build: .
    env_file: .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
    # Default command
    command: python --version